common_args:
  training_type: "cross_silo"
  random_seed: 0
  scenario: "horizontal"
  using_mlops: false
  config_version: release

environment_args:
  bootstrap: config/bootstrap.sh

data_args:
  dataset: "cifar10"
  data_cache_dir: ~/fedml_data
  partition_method: "hetero"
  partition_alpha: 0.5
  preprocessed: false 

model_args:
  model: "cnn"
  model_file_cache_folder: "./model_file_cache" 
  global_model_file_path: "./model_file_cache/global_model.pt"
  custom_client_selection: true
  client_selection_method: "random"
  server_mac_address: "d8:3a:dd:21:e6:12"

train_args:
  federated_optimizer: "FedAvg"
  client_id_list:
  client_num_in_total: 2
  client_num_per_round: 1
  comm_round: 10
  epochs: 20
  batch_size: 4
  client_optimizer: adam
  learning_rate: 0.001
  weight_decay: 0.001

validation_args:
  frequency_of_the_test: 1

device_args:
  worker_num: 1
  using_gpu: false

comm_args:
  backend: "MQTT_S3"
  mqtt_broker: "192.168.123.4"
  broker_username: "jetson"
  broker_password: "jetson"  

tracking_args:
  log_file_dir: ./log
  enable_wandb: true
  wandb_key: 7a0c8bb3ad2fcce7be9aac88060c2e71d3ff96cc
  wandb_project: fedml
  wandb_name: fedml_system_selection
