wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.11.0
    start_time: 1689828036.611504
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.11.0
      5: 0.13.2
      8:
      - 3
      - 5
backend:
  desc: null
  value: sp
batch_size:
  desc: null
  value: 10
client_id_list:
  desc: null
  value: null
client_num_in_total:
  desc: null
  value: 10
client_num_per_round:
  desc: null
  value: 5
client_optimizer:
  desc: null
  value: sgd
comm_round:
  desc: null
  value: 3
data_cache_dir:
  desc: null
  value: C:\Users\Sony/fedml_data
dataset:
  desc: null
  value: mnist
enable_wandb:
  desc: null
  value: true
epochs:
  desc: null
  value: 5
federated_optimizer:
  desc: null
  value: FedAvg
frequency_of_the_test:
  desc: null
  value: 1
gpu_mapping_file:
  desc: null
  value: config/gpu_mapping.yaml
gpu_mapping_key:
  desc: null
  value: mapping_default
is_mobile:
  desc: null
  value: 0
learning_rate:
  desc: null
  value: 0.03
local_rank:
  desc: null
  value: 0
log_file_dir:
  desc: null
  value: ./log
model:
  desc: null
  value: lr
node_rank:
  desc: null
  value: 0
partition_alpha:
  desc: null
  value: 0.5
partition_method:
  desc: null
  value: hetero
random_seed:
  desc: null
  value: 0
rank:
  desc: null
  value: 0
role:
  desc: null
  value: client
run_id:
  desc: null
  value: '0'
sys_perf_profiling:
  desc: null
  value: true
training_type:
  desc: null
  value: simulation
using_gpu:
  desc: null
  value: false
using_mlops:
  desc: null
  value: false
wandb_key:
  desc: null
  value: 7a0c8bb3ad2fcce7be9aac88060c2e71d3ff96cc
wandb_name:
  desc: null
  value: fedml_torch_fedavg_shakespeare_lr
wandb_project:
  desc: null
  value: fedml
weight_decay:
  desc: null
  value: 0.001
worker_num:
  desc: null
  value: 0
yaml_config_file:
  desc: null
  value: .\config\simulation\fedml_config.yaml
yaml_paths:
  desc: null
  value:
  - .\config\simulation\fedml_config.yaml
