common_args:
  training_type: "simulation"
  random_seed: 0

data_args:
  dataset: "mnist"
  data_cache_dir: ~/fedml_data
  partition_method: "hetero"
  partition_alpha: 0.5

model_args:
  model: "lr"

train_args:
  federated_optimizer: "FedAvg"
  client_id_list:
  client_num_in_total: 10
  client_num_per_round: 5
  comm_round: 3
  epochs: 5
  batch_size: 10
  client_optimizer: sgd
  learning_rate: 0.03
  weight_decay: 0.001

validation_args:
  frequency_of_the_test: 1

device_args:
  worker_num: 0
  using_gpu: false
  gpu_mapping_file: config/gpu_mapping.yaml
  gpu_mapping_key: mapping_default

comm_args:
  backend: "sp"
  is_mobile: 0

tracking_args:
  log_file_dir: ./log
  enable_wandb: true
  wandb_key: 7a0c8bb3ad2fcce7be9aac88060c2e71d3ff96cc
  wandb_project: fedml
  wandb_name: fedml_torch_fedavg_shakespeare_lr
  using_mlops: false