common_args:
  training_type: "cross_silo"
  scenario: "horizontal"
  using_mlops: false
  random_seed: 0

environment_args:
  bootstrap: config/bootstrap.sh

data_args:
  dataset: "cifar10"
  data_cache_dir: ~/fedml_data
  partition_method: "hetero-proportional"
  partition_alpha: 0.5
  client_proportions: "[0.85, 0.1, 0.05]"

model_args:
  model: "resnet18"
  image_size:
  input_size: 3
  class_num: 10
  model_file_cache_folder: "./model_file_cache" # will be filled by the server automatically
  global_model_file_path: "./model_file_cache/global_model.pt"

train_args:
  federated_optimizer: "FedAvg"
  client_id_list:
  client_num_in_total: 3
  client_num_per_round: 3
  comm_round: 2
  epochs: 5
  lr: 0.03
  batch_size: 10
  client_optimizer: sgd
  weight_decay: 0.001

validation_args:
  frequency_of_the_test: 1

device_args:
  worker_num: 3
  using_gpu: false
  gpu_mapping_file: config/gpu_mapping.yaml
  gpu_mapping_key: mapping_default

comm_args:
  backend: "MQTT_S3"
  mqtt_config_path: config/mqtt_config.yaml
  s3_config_path: config/s3_config.yaml

tracking_args:
  log_file_dir: ./log
  enable_wandb: true
  wandb_key: 7a0c8bb3ad2fcce7be9aac88060c2e71d3ff96cc
  wandb_project: fedml
  wandb_name: fedml_torch_image_classification
